import {
  Home,
  Users,
  UserPlus,
  ArrowLeftRight,
  Zap,
  TrendingUp,
  LineChart,
  FileText,
  Scale,
  Calculator,
  MessageSquare,
  Star,
  BellRing,
  ClipboardList,
  BarChart3,
  Banknote,
  UsersRound,
  Building2,
  ShieldCheck,
  Sparkles,
  Upload,
  Database,
  Globe,
  Settings,
  HelpCircle,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Sun,
  Moon,
  RefreshCw,
  Search,
  LayoutGrid,
  Cpu,
  UserCircle,
  Palette,
  LogOut,
  Leaf,
  Clock,
  Briefcase,
  Heart,
  ScrollText,
  Settings2,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  'home': Home,
  'users': Users,
  'user-plus': UserPlus,
  'arrows': ArrowLeftRight,
  'insights': Zap,
  'trending-up': TrendingUp,
  'chart': LineChart,
  'document': FileText,
  'scale': Scale,
  'calculator': Calculator,
  'message': MessageSquare,
  'star': Star,
  'bell-alert': BellRing,
  'clipboard': ClipboardList,
  'chart-bar': BarChart3,
  'banknotes': Banknote,
  'user-group': UsersRound,
  'building': Building2,
  'shield-check': ShieldCheck,
  'sparkles': Sparkles,
  'upload': Upload,
  'bse': Database,
  'nmf': Globe,
  'settings': Settings,
  'help': HelpCircle,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'sun': Sun,
  'moon': Moon,
  'refresh': RefreshCw,
  'search': Search,
  'grid': LayoutGrid,
  'cpu': Cpu,
  'user-circle': UserCircle,
  'palette': Palette,
  'logout': LogOut,
  'leaf': Leaf,
  'clock': Clock,
  'briefcase': Briefcase,
  'arrows-exchange': ArrowLeftRight,
  'heartbeat': Heart,
  'scroll': ScrollText,
  'cog': Settings2,
}

const NavIcon = ({ name, className = "w-5 h-5" }: { name: string; className?: string }) => {
  const IconComponent = iconMap[name]
  if (!IconComponent) return null
  return <IconComponent className={className} strokeWidth={1.5} />
}

export default NavIcon
