# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ml_service_pb2 as ml__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub(object):
    """ML Service - Investment Portfolio AI
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyProfile = channel.unary_unary(
                '/ml_service.MLService/ClassifyProfile',
                request_serializer=ml__service__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=ml__service__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.GetRecommendations = channel.unary_unary(
                '/ml_service.MLService/GetRecommendations',
                request_serializer=ml__service__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=ml__service__pb2.RecommendationResponse.FromString,
                _registered_method=True)
        self.OptimizePortfolio = channel.unary_unary(
                '/ml_service.MLService/OptimizePortfolio',
                request_serializer=ml__service__pb2.OptimizeRequest.SerializeToString,
                response_deserializer=ml__service__pb2.OptimizeResponse.FromString,
                _registered_method=True)
        self.AssessRisk = channel.unary_unary(
                '/ml_service.MLService/AssessRisk',
                request_serializer=ml__service__pb2.RiskRequest.SerializeToString,
                response_deserializer=ml__service__pb2.RiskResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ml_service.MLService/HealthCheck',
                request_serializer=ml__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=ml__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class MLServiceServicer(object):
    """ML Service - Investment Portfolio AI
    """

    def ClassifyProfile(self, request, context):
        """Classify user profile into investment persona
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendations(self, request, context):
        """Get fund recommendations based on persona
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizePortfolio(self, request, context):
        """Optimize portfolio allocation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssessRisk(self, request, context):
        """Assess portfolio risk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyProfile,
                    request_deserializer=ml__service__pb2.ClassifyRequest.FromString,
                    response_serializer=ml__service__pb2.ClassifyResponse.SerializeToString,
            ),
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=ml__service__pb2.RecommendationRequest.FromString,
                    response_serializer=ml__service__pb2.RecommendationResponse.SerializeToString,
            ),
            'OptimizePortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizePortfolio,
                    request_deserializer=ml__service__pb2.OptimizeRequest.FromString,
                    response_serializer=ml__service__pb2.OptimizeResponse.SerializeToString,
            ),
            'AssessRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.AssessRisk,
                    request_deserializer=ml__service__pb2.RiskRequest.FromString,
                    response_serializer=ml__service__pb2.RiskResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ml__service__pb2.HealthRequest.FromString,
                    response_serializer=ml__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml_service.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml_service.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """ML Service - Investment Portfolio AI
    """

    @staticmethod
    def ClassifyProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/ClassifyProfile',
            ml__service__pb2.ClassifyRequest.SerializeToString,
            ml__service__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/GetRecommendations',
            ml__service__pb2.RecommendationRequest.SerializeToString,
            ml__service__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizePortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/OptimizePortfolio',
            ml__service__pb2.OptimizeRequest.SerializeToString,
            ml__service__pb2.OptimizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssessRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/AssessRisk',
            ml__service__pb2.RiskRequest.SerializeToString,
            ml__service__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/HealthCheck',
            ml__service__pb2.HealthRequest.SerializeToString,
            ml__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
