/**
 * Maps slugified provider IDs to AMC metadata (logo URL, website).
 * Provider IDs are generated by slugify(fundHouseName) in fund-sync.service.ts.
 *
 * Logo URLs point to Next.js public directory assets.
 * Actual PNG files can be added later — this mapping establishes the infrastructure.
 */
export const PROVIDER_METADATA: Record<string, { logoUrl: string; websiteUrl: string }> = {
  'aditya-birla-sun-life-mutual-fund': {
    logoUrl: '/images/amcs/aditya-birla-sun-life.png',
    websiteUrl: 'https://mutualfund.adityabirlacapital.com',
  },
  'axis-mutual-fund': {
    logoUrl: '/images/amcs/axis.png',
    websiteUrl: 'https://www.axismf.com',
  },
  'bajaj-finserv-mutual-fund': {
    logoUrl: '/images/amcs/bajaj-finserv.png',
    websiteUrl: 'https://www.bajajamc.com',
  },
  'bandhan-mutual-fund': {
    logoUrl: '/images/amcs/bandhan.png',
    websiteUrl: 'https://www.bandhanmutual.com',
  },
  'bank-of-india-mutual-fund': {
    logoUrl: '/images/amcs/bank-of-india.png',
    websiteUrl: 'https://www.boimf.in',
  },
  'baroda-bnp-paribas-mutual-fund': {
    logoUrl: '/images/amcs/baroda-bnp-paribas.png',
    websiteUrl: 'https://www.barodabnpparibasmf.in',
  },
  'canara-robeco-mutual-fund': {
    logoUrl: '/images/amcs/canara-robeco.png',
    websiteUrl: 'https://www.canararobeco.com',
  },
  'dsp-mutual-fund': {
    logoUrl: '/images/amcs/dsp.png',
    websiteUrl: 'https://www.dspim.com',
  },
  'edelweiss-mutual-fund': {
    logoUrl: '/images/amcs/edelweiss.png',
    websiteUrl: 'https://www.edelweissmf.com',
  },
  'franklin-templeton-mutual-fund': {
    logoUrl: '/images/amcs/franklin-templeton.png',
    websiteUrl: 'https://www.franklintempletonindia.com',
  },
  'groww-mutual-fund': {
    logoUrl: '/images/amcs/groww.png',
    websiteUrl: 'https://www.growwmf.in',
  },
  'hdfc-mutual-fund': {
    logoUrl: '/images/amcs/hdfc.png',
    websiteUrl: 'https://www.hdfcfund.com',
  },
  'hsbc-mutual-fund': {
    logoUrl: '/images/amcs/hsbc.png',
    websiteUrl: 'https://www.assetmanagement.hsbc.co.in',
  },
  'icici-prudential-mutual-fund': {
    logoUrl: '/images/amcs/icici-prudential.png',
    websiteUrl: 'https://www.icicipruamc.com',
  },
  'invesco-mutual-fund': {
    logoUrl: '/images/amcs/invesco.png',
    websiteUrl: 'https://www.invescomutualfund.com',
  },
  'iti-mutual-fund': {
    logoUrl: '/images/amcs/iti.png',
    websiteUrl: 'https://www.itimf.com',
  },
  'jm-financial-mutual-fund': {
    logoUrl: '/images/amcs/jm-financial.png',
    websiteUrl: 'https://www.jmfinancialmf.com',
  },
  'kotak-mahindra-mutual-fund': {
    logoUrl: '/images/amcs/kotak-mahindra.png',
    websiteUrl: 'https://www.kotakmf.com',
  },
  'lic-mutual-fund': {
    logoUrl: '/images/amcs/lic.png',
    websiteUrl: 'https://www.licmf.com',
  },
  'mahindra-manulife-mutual-fund': {
    logoUrl: '/images/amcs/mahindra-manulife.png',
    websiteUrl: 'https://www.mahindramanulifemf.com',
  },
  'mirae-asset-mutual-fund': {
    logoUrl: '/images/amcs/mirae-asset.png',
    websiteUrl: 'https://www.maboraassetmf.co.in',
  },
  'motilal-oswal-mutual-fund': {
    logoUrl: '/images/amcs/motilal-oswal.png',
    websiteUrl: 'https://www.motilaloswalmf.com',
  },
  'navi-mutual-fund': {
    logoUrl: '/images/amcs/navi.png',
    websiteUrl: 'https://www.navimutualfund.com',
  },
  'nippon-india-mutual-fund': {
    logoUrl: '/images/amcs/nippon-india.png',
    websiteUrl: 'https://mf.nipponindiaim.com',
  },
  'old-bridge-mutual-fund': {
    logoUrl: '/images/amcs/old-bridge.png',
    websiteUrl: 'https://www.oldbridgemutualfund.com',
  },
  'pgim-india-mutual-fund': {
    logoUrl: '/images/amcs/pgim-india.png',
    websiteUrl: 'https://www.pgimindiamf.com',
  },
  'ppfas-mutual-fund': {
    logoUrl: '/images/amcs/ppfas.png',
    websiteUrl: 'https://amc.ppfas.com',
  },
  'quant-mutual-fund': {
    logoUrl: '/images/amcs/quant.png',
    websiteUrl: 'https://www.quantmutual.com',
  },
  'quantum-mutual-fund': {
    logoUrl: '/images/amcs/quantum.png',
    websiteUrl: 'https://www.quantumamc.com',
  },
  'sbi-mutual-fund': {
    logoUrl: '/images/amcs/sbi.png',
    websiteUrl: 'https://www.sbimf.com',
  },
  'shriram-mutual-fund': {
    logoUrl: '/images/amcs/shriram.png',
    websiteUrl: 'https://www.shriramamc.com',
  },
  'sundaram-mutual-fund': {
    logoUrl: '/images/amcs/sundaram.png',
    websiteUrl: 'https://www.sundarammutual.com',
  },
  'tata-mutual-fund': {
    logoUrl: '/images/amcs/tata.png',
    websiteUrl: 'https://www.tatamutualfund.com',
  },
  'taurus-mutual-fund': {
    logoUrl: '/images/amcs/taurus.png',
    websiteUrl: 'https://www.taurusmutualfund.com',
  },
  'trust-mutual-fund': {
    logoUrl: '/images/amcs/trust.png',
    websiteUrl: 'https://www.trustmf.com',
  },
  'union-mutual-fund': {
    logoUrl: '/images/amcs/union.png',
    websiteUrl: 'https://www.unionmf.com',
  },
  'uti-mutual-fund': {
    logoUrl: '/images/amcs/uti.png',
    websiteUrl: 'https://www.utimf.com',
  },
  'whiteoak-capital-mutual-fund': {
    logoUrl: '/images/amcs/whiteoak-capital.png',
    websiteUrl: 'https://www.whiteoakamc.com',
  },
  'zerodha-mutual-fund': {
    logoUrl: '/images/amcs/zerodha.png',
    websiteUrl: 'https://coin.zerodha.com',
  },
  '360-one-mutual-fund': {
    logoUrl: '/images/amcs/360-one.png',
    websiteUrl: 'https://www.360onemf.com',
  },
  'helios-mutual-fund': {
    logoUrl: '/images/amcs/helios.png',
    websiteUrl: 'https://www.heliosmf.in',
  },
  'samco-mutual-fund': {
    logoUrl: '/images/amcs/samco.png',
    websiteUrl: 'https://www.samcomf.com',
  },
  'nj-mutual-fund': {
    logoUrl: '/images/amcs/nj.png',
    websiteUrl: 'https://www.njmutualfund.com',
  },
  'mahi-mutual-fund-erstwhile-boi-axa-': {
    logoUrl: '/images/amcs/mahi.png',
    websiteUrl: 'https://www.mahimutualfund.com',
  },
}
